//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica
{
    public partial class Gestion
    {
        protected global::System.Web.UI.WebControls.Panel pnlAccesoRestringido;
        protected global::System.Web.UI.WebControls.Panel pnlAdmin;

        protected global::SistemaReservasEstetica.Controls.GestionServicios ucGestServ;
        protected global::SistemaReservasEstetica.Controls.GestionProfesionales ucGestProf;
        protected global::SistemaReservasEstetica.Controls.AgendaProfesional ucAgendaGlobal;
    }
}
