//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica
{
    public partial class Reservas
    {
        /// <summary>
        /// Control mvRoles.
        /// </summary>
        protected global::System.Web.UI.WebControls.MultiView mvRoles;

        /// <summary>
        /// Control viewCliente.
        /// </summary>
        protected global::System.Web.UI.WebControls.View viewCliente;

        /// <summary>
        /// WebPart: Catálogo de servicios (vista Cliente).
        /// </summary>
        protected global::SistemaReservasEstetica.Controls.CatalogoServicios ucCatalogoCliente;

        /// <summary>
        /// WebPart: Calendario de disponibilidad (vista Cliente).
        /// </summary>
        protected global::SistemaReservasEstetica.Controls.CalendarioDisponibilidad ucCalendarioCliente;

        /// <summary>
        /// WebPart: Formulario de reserva (vista Cliente).
        /// </summary>
        protected global::SistemaReservasEstetica.Controls.FormularioReserva ucFormularioCliente;

        /// <summary>
        /// Control viewProfesional.
        /// </summary>
        protected global::System.Web.UI.WebControls.View viewProfesional;

        /// <summary>
        /// WebPart: Agenda del profesional.
        /// </summary>
        protected global::SistemaReservasEstetica.Controls.AgendaProfesional ucAgendaProf;

        /// <summary>
        /// Control viewAdmin.
        /// </summary>
        protected global::System.Web.UI.WebControls.View viewAdmin;

        /// <summary>
        /// WebPart: Catálogo de servicios (vista Admin).
        /// </summary>
        protected global::SistemaReservasEstetica.Controls.CatalogoServicios ucCatalogoAdmin;

        /// <summary>
        /// WebPart: Agenda global (vista Admin).
        /// </summary>
        protected global::SistemaReservasEstetica.Controls.AgendaProfesional ucAgendaAdmin;
    }
}
