//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica.Controls
{
    public partial class AgendaProfesional
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlProfesional;
        protected global::System.Web.UI.WebControls.Button btnHoy;
        protected global::System.Web.UI.WebControls.Button btnTodas;
        protected global::System.Web.UI.WebControls.GridView gvAgenda;
    }
}
