//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica.Controls
{
    public partial class CalendarioDisponibilidad
    {
        /// <summary>
        /// Control btnActualizar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnActualizar;

        /// <summary>
        /// Control tblHorarios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Table tblHorarios;
    }
}
