//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica.Controls
{
    public partial class CatalogoServicios
    {
        /// <summary>
        /// Control rptServicios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptServicios;
    }
}
