//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica.Controls
{
    public partial class FormularioReserva
    {
        protected global::System.Web.UI.WebControls.ValidationSummary vsReserva;
        protected global::System.Web.UI.WebControls.Panel pnlConfirmacion;
        protected global::System.Web.UI.WebControls.Label lblConfirmacion;

        protected global::System.Web.UI.WebControls.TextBox txtNombreCliente;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNombre;

        protected global::System.Web.UI.WebControls.DropDownList ddlServicios;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvServicio;

        protected global::System.Web.UI.WebControls.DropDownList ddlProfesional;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvProfesional;

        protected global::System.Web.UI.WebControls.TextBox txtFechaHora;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFecha;
        protected global::System.Web.UI.WebControls.CustomValidator cvFechaFutura;

        protected global::System.Web.UI.WebControls.Button btnVerificar;
        protected global::System.Web.UI.WebControls.Button btnReservar;
        protected global::System.Web.UI.WebControls.Button btnLimpiar;
    }
}
