//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica.Controls
{
    public partial class GestionProfesionales
    {
        protected global::System.Web.UI.WebControls.GridView gvProfesionales;
        protected global::System.Web.UI.WebControls.ValidationSummary vsNuevoProf;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNombre;

        protected global::System.Web.UI.WebControls.TextBox txtEspecialidad;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEspecialidad;

        protected global::System.Web.UI.WebControls.Button btnAgregar;
    }
}
