//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasEstetica.Controls
{
    public partial class GestionServicios
    {
        protected global::System.Web.UI.WebControls.GridView gvServicios;
        protected global::System.Web.UI.WebControls.ValidationSummary vsNuevoServicio;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;

        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescripcion;

        protected global::System.Web.UI.WebControls.TextBox txtDuracion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDuracion;
        protected global::System.Web.UI.WebControls.RangeValidator rvDuracion;

        protected global::System.Web.UI.WebControls.TextBox txtPrecio;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPrecio;
        protected global::System.Web.UI.WebControls.CompareValidator cvPrecio;

        protected global::System.Web.UI.WebControls.Button btnAgregar;
    }
}
